services:
  - type: web
    name: store-rating-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: store-rating-db
          property: connectionString
      - key: FRONTEND_URL
        value: https://store-rating-frontend.onrender.com

  - type: web
    name: store-rating-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://store-rating-backend.onrender.com

databases:
  - name: store-rating-db
    databaseName: store_rating_prod
    user: store_rating_user
